config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  authenticate :admin, ->(a) { a.is_a?(Admin) } do
    mount Sidekiq::Web => '/sidekiq'
  end
  mount RailsAdmin::Engine => '/cms', as: 'rails_admin'
  root to: 'home#index'
  get  'catalog',            to: 'books#index'
  get 'search',              to: 'search#search'
  get  'settings/addresses', to: 'addresses#index'
  post 'settings/addresses', to: 'addresses#create'
  put  'settings/addresses', to: 'addresses#update'
  get  'settings/privacy',   to: 'users#edit'

  resource :user, only: %i[edit] do
    collection do
      patch 'update_email'
      patch 'update_password'
    end
  end

  resources :books, only: %i[index show update] do
    resources :reviews, only: :create
  end
  resource  :cart, only: %i[show update]
  resources :checkout
  resources :credit_card
  resources :orders, only: %i[index show]
  resources :order_items, only: %i[create update destroy]

  devise_for :admins
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :omniauthable, omniauth_providers: [:facebook]

  attr_accessor :skip_password_validation

  validates :email,
            presence: true,
            format: { with: /@/,
                      message: 'ivalid format' }

  validates :password,
            format: { with: /\A\S(?=.*\d)(?=.*[a-z])(?=.*[A-Z])\S*\z/i,
                      message: 'should contain at least 1 uppercase, at least \
                      1 lowercase, at least 1 number and no whitespeses.' },
            unless: :skip_password_validation

  has_many :orders, dependent: :destroy
  has_many :order_items, through: :orders, dependent: :destroy
  has_many :books, through: :order_items, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :addresses, dependent: :destroy

  has_one :billing, dependent: :destroy
  has_one :shipping, dependent: :destroy
  has_one :credit_card, dependent: :destroy

  mount_uploader :avatar, AvatarUploader

  before_save do |user|
    unless user.billing.nil?
      user.name = name_from_address if user.name.nil?
    end

    unless user.avatar_url.present? || user.provider == 'facebook' || user.remote_avatar_url.present?
      av_name = user.name || user.email
      av_img = LetterAvatar.generate av_name, 200

      File.open(av_img) do |f|
        user.avatar = f
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
      user.remote_avatar_url = auth.info.image
      user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if (data = session['devise.facebook_data']) && session['devise.facebook_data']['extra']['raw_info']
        user.email = data['email'] if user.email.blank?
      end
    end
  end

  private

  def name_from_address
    "#{billing.first_name} #{billing.last_name}"
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(omniauth_params)

      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
        set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
      else
        session['devise.facebook_data'] = omniauth_params
        redirect_to new_user_registration_url
      end
    end

    def failure
      redirect_to root_path
    end

    private

    def omniauth_params
      request.env['omniauth.auth']
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_user

  def edit; end

  def update_email
    skip_user_checks!
    if @user.update_without_password(user_params)
      bypass_sign_in(@user)
      flash[:success] = 'Email successfuly changed'
      redirect_to settings_privacy_path
    else
      flash[:danger] = @user.errors.full_messages.to_sentence
      render :edit
    end
  end

  def update_password
    if @user.update_with_password(user_params)
      bypass_sign_in(@user)
      flash[:success] = 'Password successfuly changed'
      redirect_to settings_privacy_path
    else
      flash[:danger] = @user.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :current_password, :password, :password_confirmation)
  end

  def set_user
    @user = current_user
  end

  def skip_user_checks!
    @user.skip_password_validation = true
    @user.skip_confirmation!
    @user.skip_reconfirmation!
  end
end

app/views/users/_edit_email.haml
%p.in-gold-500.font-18.mb-25 Email
= form_for(@user, url: { action: "update_email" }, html: {class: 'general-form-md email' }) do |f|
  .form-group.mb-35
    = f.label :email, 'Enter Email', class: 'control-label input-label'
    = f.email_field :email, autofocus: true, autocomplete: "off", class: 'form-control', value: current_user.email
  .general-text-align
    = f.submit 'Save', class: 'btn btn-default mb-35'

app/views/users/_edit_password.haml
%p.in-gold-500.font-18.mb-25 Password
= form_for(@user, url: { action: "update_password" }, html: { class: 'general-form-md divider-lg-bottom pb-25'}) do |f|
  .form-group.mb-30
    = f.label :current_password, 'Old Password', class: "control-label input-label"
    = f.password_field :current_password, class: "form-control", autocomplete: "off", placeholder: 'Old Password'
  .form-group.mb-30
    = f.label :password, 'New Password', class: "control-label input-label"
    = f.password_field :password, class: "form-control", autofocus: true, autocomplete: "off", placeholder: 'New Password'
  .form-group.mb-40
    = f.label :password_confirmation, 'Confirm Password', class: "control-label input-label"
    = f.password_field :password_confirmation, autocomplete: "off", class: "form-control", placeholder: 'Confirm Password'
  .general-text-align
    = f.submit 'Save', class: 'btn btn-default mb-10'

app/views/users/_remove_account.haml
%p.in-gold-500.font-18.mb-25 Remove Account
.general-settings-btn
  = button_to 'Remove Account', registration_path(@user), class: 'btn btn-default mb-20', data: { confirm: "Are you sure?" }, method: :delete
.form-group.checkbox.general-settings-checkbox
  %label.checkbox-label#remove_account
    %input.checkbox-input{type: "checkbox", hidden: "true"}
    %span.checkbox-icon
      %i.fa.fa-check
    %span.checkbox-text I understand that all data will be lost

app/views/users/edit.html.haml
%main.container
  %h1.general-title-margin Settings
  %ul.nav.clearfix.mb-20{role: "tablist"}
    %li.tab-item{role: "presentation"}
      = link_to 'Address', settings_addresses_path, class: 'tab-link'
    %li.tab-item{role: "presentation"}
      = link_to 'Privacy', settings_privacy_path, class: 'tab-link filter-link active'
  .tab-content
    .row.mb-60
      .col-sm-5
        = render 'users/edit_email'
      .col-sm-5.col-sm-offset-1
        = render 'users/edit_password'
      .col-sm-12
        = render 'users/remove_account'