config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  authenticate :admin, ->(a) { a.is_a?(Admin) } do
    mount Sidekiq::Web => '/sidekiq'
  end
  mount RailsAdmin::Engine => '/cms', as: 'rails_admin'
  root to: 'home#index'
  get  'catalog',            to: 'books#index'
  get 'search',              to: 'search#search'
  get  'settings/addresses', to: 'addresses#index'
  post 'settings/addresses', to: 'addresses#create'
  put  'settings/addresses', to: 'addresses#update'
  get  'settings/privacy',   to: 'users#edit'

  resource :user, only: %i[edit] do
    collection do
      patch 'update_email'
      patch 'update_password'
    end
  end

  resources :books, only: %i[index show update] do
    resources :reviews, only: :create
  end
  resource  :cart, only: %i[show update]
  resources :checkout
  resources :credit_card
  resources :orders, only: %i[index show]
  resources :order_items, only: %i[create update destroy]

  devise_for :admins
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  belongs_to :category
  has_many :authorships, dependent: :destroy
  has_many :authors, through: :authorships, dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :images, dependent: :destroy

  validates :title, presence: true, uniqueness: true
  validates :price, presence: true, numericality: true
  validates :height, :width, :depth, numericality: true

  paginates_per 12

  mount_uploader :cover, ImageUploader

  scope :by_category, ->(category_id) { where category_id: category_id }

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  settings index: { number_of_shards: 4 } do
    mapping dynamic: false do
      indexes :id, type: :integer

      indexes :title, type: 'text' do
        indexes :title
        indexes :raw, type: 'keyword'
      end

      indexes :description, type: :text
      indexes :isbn, type: :text
      indexes :price, type: :float
      indexes :publication_year, type: :integer
      indexes :created_at, type: :date
      indexes :sales, type: :integer
      indexes :cover_url, type: :text

      indexes :category, type: :object do
        indexes :id
        indexes :name
      end

      indexes :authors, type: :nested do
        indexes :id
        indexes :first_name
        indexes :last_name
      end
    end
  end

  def as_indexed_json(_options = nil) # rubocop:disable Metrics/MethodLength
    as_json(
      only: %i[
        id
        title
        description
        isbn
        publication_year
        price
        materials
        created_at
      ],
      methods: %i[cover_url sales],
      include: {
        authors: { only: %i[id first_name last_name] },
        category: { only: %i[id name] }
      }
    )
  end

  def sales
    orders.payed.map { |order| order.order_items.sum(:quantity) }.sum
  end

  def self.best_sellers
    best = Order.payed.joins(:order_items).group(:book_id)
                .order('sum("order_items"."quantity") DESC').count.keys
    Book.find(best)
  end
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  def show
    @order = Order.new(order_item_ids: session[:order_item_ids],
                       coupon_id: session[:coupon_id])
  end

  def update
    session[:coupon_id] = coupon.id if coupon

    redirect_to cart_path, notice: coupon ? 'Coupon applied' : 'Invalid coupon'
  end

  private

  def coupon
    @coupon ||= Coupon.find_by(active: true, code: params[:code])
  end
end

app/views/carts/_order_items.html.haml
%table.table.table-hover
  %tr.no-hover
    %th.col-pic.pl-0
      %span.in-grey-600 Product
    %th.col-title
    %th.col-price
      %span.in-grey-600 Price
    %th.col-quantity
      %span.in-grey-600 Quantity
    %th.col-total
      %span.in-grey-600 SubTotal
    %th.col-close
  - @order.order_items.each do |order_item|
    %tr
      %td
        .general-img-wrap-table
          = link_to book_path(order_item.book) do
            = image_tag(order_item.book.cover, class: "cart-img-shadow pull-left", alt: "design-book")
      %td
        = link_to book_path(order_item.book), class: 'title-link' do
          %p.title= order_item.book.title
      %td
        %span.font-16.in-gold-500= number_to_euro order_item.book.price
      %td
        = render 'carts/quantity', order_item: order_item
      %td
        %span.font-16.in-gold-500= number_to_euro order_item.total 
      %td
        = button_to order_item, method: :delete, class: 'close general-cart-close' do
          %span{'aria-hidden': "true"} &times;

app/views/carts/_order_items_xs.html.haml
- @order.order_items.each do |order_item|
  .general-cart-item.divider-lg-bottom
    = button_to order_item, method: :delete, class: 'close general-cart-close' do
      %span{'aria-hidden': "true"} &times;
    .general-img-wrap-table
      = link_to book_path(order_item.book) do
        = image_tag(order_item.book.cover, class: "cart-img-shadow", alt: "design-book")
    = link_to book_path(order_item.book), class: 'title-link' do
      %p.title= order_item.book.title
    %table.table
      %tr
        %td
          %span.in-grey-600 Price
        %td
          %span.font-16.in-gold-500= number_to_euro order_item.book.price
      %tr
        %td.vertical-middle
          %span.in-grey-600 Quantity
        %td
          = render 'carts/quantity', order_item: order_item
      %tr
        %td
          %span.in-grey-600 SubTotal
        %td
          %span.font-16.in-gold-500= number_to_euro order_item.total

app/views/carts/_quantity.html.haml
.input-group
  = form_for order_item, method: :put do |form|
    = link_to order_item_path(id: order_item.id, order_item: {quantity: order_item.quantity - 1}), :method => :put, class: 'input-link pt-7' do
      %i.fa.fa-minus.line-heaght-40
    = form.text_field :quantity, value: order_item.quantity, class: "form-control quantity-input"
    = link_to order_item_path(id: order_item.id, order_item: {quantity: order_item.quantity + 1}), :method => :put, class: 'input-link pt-7' do
      %i.fa.fa-plus.line-heaght-40

app/views/carts/show.html.haml
%main.container.general-main-wrap
  %h1.general-title-margin Cart
  - items = OrderItem.where(id: session[:order_item_ids])
  - if items.empty?
    .text-center
      %p.font-18 Cart is empty
      = link_to "Go to Store", catalog_path(), class: "btn btn-default mb-20"
  - else
    .visible-xs
      = render 'order_items_xs'
    .hidden-xs
      = render 'order_items'
    .general-order-wrap
      .row
        .col-sm-4
          .input-group.general-input-group
            = form_tag cart_path, method: :put
            = label_tag :code, 'Enter Your Coupon Code', class: 'input-label'
            = text_field_tag(:code, nil, placeholder: 'Enter Your Coupon Code', class: 'form-control mb-30')
            %div
              = submit_tag 'Apply Coupon', class: 'btn btn-primary mb-15 res-block'
        .col-sm-8
          .res-mr-200.text-center.general-text-right
            %p.in-gold-500.font-18 Order Summary
            %table.general-summary-table.general-summary-table-right.general-text-right
              = render 'checkout/order_summary', order: @order
            = link_to "Checkout", checkout_path(:login), class: "btn btn-default mb-20 visible-xs-inline-block"
    .text-center
      = link_to "Checkout", checkout_path(:login), class: "btn btn-default mb-20 hidden-xs"