config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  authenticate :admin, ->(a) { a.is_a?(Admin) } do
    mount Sidekiq::Web => '/sidekiq'
  end
  mount RailsAdmin::Engine => '/cms', as: 'rails_admin'
  root to: 'home#index'
  get  'catalog',            to: 'books#index'
  get 'search',              to: 'search#search'
  get  'settings/addresses', to: 'addresses#index'
  post 'settings/addresses', to: 'addresses#create'
  put  'settings/addresses', to: 'addresses#update'
  get  'settings/privacy',   to: 'users#edit'

  resource :user, only: %i[edit] do
    collection do
      patch 'update_email'
      patch 'update_password'
    end
  end

  resources :books, only: %i[index show update] do
    resources :reviews, only: :create
  end
  resource  :cart, only: %i[show update]
  resources :checkout
  resources :credit_card
  resources :orders, only: %i[index show]
  resources :order_items, only: %i[create update destroy]

  devise_for :admins
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_order

  protected

  def after_sign_in_path_for(resource)
    if cookies[:from_checkout]
      cookies.delete :from_checkout
      checkout_path(:addresses)
    else
      super
    end
  end

  private

  def current_order
    return Order.new unless session[:order_id]
    Order.find(session[:order_id])
  end

  def current_ability
    @current_ability ||= Ability.new(current_user, session)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def categories
    Category.order('name')
  end

  def cart_items_count
    return OrderItem.where(id: session[:order_item_ids]).sum(:quantity) if session[:order_item_ids]
    current_order.order_items.sum(:quantity)
  end

  def number_to_euro(amount)
    number_to_currency(amount, unit: '€')
  end
end

app/views/application/_flash.haml
%section
  .container
    - flash.each do |type, message|
      .alert.alert-dismissable{:class => "alert-#{type}"}
        %a.close{href: "#", 'data-dismiss': "alert", 'aria-label': "close"} &times;
        =message

app/views/application/_footer.haml
%footer.navbar-inverse
  .container
    .row
      .col-sm-9
        %ul.list-inline.general-align.mb-25
          %li
            = link_to "Home", root_path, class: "nav-link"
          %li
            = link_to "Shop", catalog_path, class: "nav-link"
          - if user_signed_in?
            %li
              = link_to "Orders", orders_path, class: "nav-link"
            %li
              = link_to "Settings", settings_addresses_path, class: "nav-link"
      .col-sm-3
        %p.general-nav-mail
          = mail_to 'support@bookstore.com', 'support@bookstore.com', class: 'general-nav-mail'
        %p.general-nav-number
          = link_to '(555)-555-5555', 'tel:5555555555', class: 'general-nav-number'
        %ul.list-inline.general-align
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-facebook{'aria-hidden': "true"}
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-twitter{'aria-hidden': "true"}
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-google-plus{'aria-hidden': "true"}
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-instagram{'aria-hidden': "true"}

app/views/application/_header.haml
%header.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle.pull-left{type: "button", 'data-toggle': "collapse", 'data-target': "#navbar"}
        %span.sr-only
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: root_path}
        %i.fa.fa-book
        %b Bookstore
      %a.shop-link.pull-right.visible-xs{href: cart_path}
        = render 'shop_icon', cached: true
    %a.shop-link.pull-right.hidden-xs{href: cart_path}
      = render 'shop_icon', cached: true
    #navbar.navbar-collapse.collapse.pl-30{'aria-expanded': "false"}
      .visible-xs
        %button.close{type: "button", 'aria-label': "Close"}
          %span{'aria-hidden': "true"} &times;
        %ul.nav.navbar-nav
          %li
            = link_to "Home", root_path
          %li
            %a{type: "button", 'data-toggle': "collapse", href: "#menu_shop", 'aria-expanded': "false", 'aria-controls': "menu_shop"} Shop
            %ul#menu_shop.collapse.list-unstyled.pl-30.mb-10{'aria-expanded': "false"}
              %li
                = link_to "All", catalog_path, class: "collapse-link"
              - categories.each do |category|
                %li
                  = link_to "#{category.name}", catalog_path(category_id: category.id), class: "collapse-link"
          - if user_signed_in?
            %li
              %a{type: "button", 'data-toggle': "collapse", href: "#menu_my_account", 'aria-expanded': "false", 'aria-controls': "menu_my_account"} My account
              %ul#menu_my_account.collapse.list-unstyled.pl-30.mb-10{'aria-expanded': "false"}
                %li
                  = link_to "Orders", orders_path, class: "collapse-link"
                %li
                  = link_to "Settings", settings_addresses_path, class: "collapse-link"
            %li
              = link_to "Log out", destroy_user_session_path, method: :delete
          - else
            %li
              = link_to "Log in", new_user_session_path 
            %li
              = link_to "Sign up", new_user_registration_path
      .hidden-xs
        %ul.nav.navbar-nav
          %li
            = link_to "Home", root_path
          %li.dropdown
            %a.dropdown-toggle{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"} Shop
            %ul.dropdown-menu
              %li
                = link_to "All", catalog_path, class: "collapse-link"
              - categories.each do |category|
                %li
                  = link_to "#{category.name}", catalog_path(category_id: category.id)
          - if user_signed_in?
            %li.dropdown
              %a.dropdown-toggle{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"} My account
              %ul.dropdown-menu
                %li
                  = link_to "Orders", orders_path
                %li
                  = link_to "Settings", settings_addresses_path
                %li.divider{role: "separator"}
                %li
                  = link_to "Log out", destroy_user_session_path, method: :delete
          - else
            %li
              = link_to "Log in", new_user_session_path
            %li
              = link_to "Sign up", new_user_registration_path

app/views/application/_shop_icon.haml
- items_count = cart_items_count
- if items_count > 0
  %span.shop-icon
    %span.shop-quantity= items_count
- else
  %span.shop-icon